Activities
alkemyTech/OT158-Node-server pull request #16
Opened 2022-03-26 12:29 UTC by Ayelen85

I create activities in all folders and make JWT

2022-03-29 22:02 UTC, manuelfrancisco requested changes

2022-03-29 22:02 UTC, manuelfrancisco commented on models/activities.js
> +      activities.belongsTo(models.Roles, {as: 'role'});
esta asociación está incorrecta, actividades perteneciendo a roles? no tiene sentido. revisá bien la tarea por las dudas

2022-03-29 22:02 UTC, manuelfrancisco commented on repositories/activities.js
> +class ActivitiesRepository {
comentamos que vamos a hacer programación funcional, esto no cumple con el paradigma. Fijate el repository de users que tenés el ejemplo de cómo hacerlo

2022-03-29 22:02 UTC, manuelfrancisco commented on repositories/activities.js
> +    async findAllActivities(){
estos no son los nombres que convenimos, además de que la tarea de modelo de actividades no te pide ningún método de repository realmente, sólo el archivo

2022-03-29 22:02 UTC, manuelfrancisco commented on services/activities.js
> +const findById = async(id) => {
lo mismo que te mencionaba en el repository, los nombres y los métodos no deberían estar siquiera, seguramente está hecho lo mismo en el controller asi que también habría que sacar los métodos

2022-03-30 19:11 UTC, Ayelen85 commented on models/activities.js
> +      activities.belongsTo(models.Roles, {as: 'role'});
Ya la modifique. Gracias por las correcciones

2022-03-30 19:11 UTC, Ayelen85 commented on repositories/activities.js
> +class ActivitiesRepository {
OK

2022-03-30 19:13 UTC, Ayelen85 commented on repositories/activities.js
> +    async findAllActivities(){
Ok. Ya lo elimine. Gracias por las correcciones

2022-03-30 19:23 UTC, Ayelen85 commented on services/activities.js
> +const findById = async(id) => {
Ok. Ya lo elimine. Gracias por las correcciones

2022-04-01 18:46 UTC, closed without merging