Model and Migrate slides
alkemyTech/OT158-Node-server pull request #18
Opened 2022-03-26 15:12 UTC by Edgar-Rios

### dificultades:
- no pude saber a que se refiere el campo order. Lo declare como string en el modelo

2022-03-30 10:28 UTC, manuelfrancisco requested changes

2022-03-30 10:28 UTC, manuelfrancisco commented on migrations/create-slide.js
> +'use strict';
tenés dos archivos de migrations, hay uno que está de más y habría que eliminarlo

2022-03-30 10:28 UTC, manuelfrancisco commented on models/slides.js
> +    order: DataTypes.STRING,
el campo order sí tiene sentido, es el orden de aparición de las slides en el front. Tiene que ser un entero

2022-03-30 10:28 UTC, manuelfrancisco commented on models/slides.js
> +    organizationId: DataTypes.INTEGER
está bien el campo de organizationId pero te falta la relación

2022-03-30 15:48 UTC, Edgar-Rios commented on models/slides.js
> +    organizationId: DataTypes.INTEGER
La relacion se la quite porque sino no me permitia hacer el testeo ya que me tiraba error porque no encontraba el modelo de Organization

2022-03-31 11:14 UTC, manuelfrancisco approved these changes

2022-04-01 21:14 UTC, merged