Ot158 16
alkemyTech/OT158-Node-server pull request #21
Opened 2022-03-26 19:19 UTC by JuanSilva27

2022-03-30 10:44 UTC, manuelfrancisco requested changes

2022-03-30 10:44 UTC, manuelfrancisco commented on models/categories.js
> +    name: DataTypes.STRING,
fijate la descripción de la tarea porque hay campos nullables y campos no nullables

2022-03-31 01:15 UTC, MatiasMinchaca commented on controllers/categories.js
> +module.exports = {
Entre los chicos hemos pensado en exportar los modulos abajo 
ejemplo :
const getAll = async () => {}
module.exports = { getAll }

2022-03-31 11:15 UTC, manuelfrancisco approved these changes

2022-03-31 11:15 UTC, manuelfrancisco commented on models/categories.js
> +'use strict';
por lo que veo también se te cruzaron los PRs, para la próxima porfa fijemonos de hacer uno por tarea

2022-03-31 21:41 UTC, merged