Ot158 27 middleware admin
alkemyTech/OT158-Node-server pull request #28
Opened 2022-03-28 18:22 UTC by Alacran86

Middleware check Admin role link:

https://alkemy-labs.atlassian.net/browse/OT158-27

2022-04-01 15:21 UTC, manuelfrancisco requested changes

2022-04-01 15:21 UTC, manuelfrancisco commented on middlewares/adminValidator.js
> +    if (!req.user) return res.status(401).json({ error: "Unauthorized" });
cómo sabés que te llega este req.user?

2022-04-01 15:21 UTC, manuelfrancisco commented on middlewares/adminValidator.js
> +    if (req.user.roleId === 1) {
sería prudente no hardcodear el id de rol administrador, sería mejor tener en algún lado común un archivo donde esté la constante del nombre del rol e ir a buscarlo por nombre a la base

2022-04-05 00:01 UTC, Alacran86 commented
Gonzalo ahi te mande un nuevo pull nose si estara bien puse el roleID en el config como variable

2022-04-06 02:44 UTC, Galaeno commented on models/users.js
> -<<<<<<< HEAD
Quedaron lineas de conflictos

2022-04-06 02:44 UTC, Galaeno commented on middlewares/adminValidator.js
> +    return res.status(401).json({
Recomiendo llevar los codigos http a un archivo de constantes para su reutilización

2022-04-06 02:44 UTC, Galaeno commented on config/config.js
> +        "roleId": process.env.ROLE_ID
Qué intención tiene ésta config?

2022-04-06 02:44 UTC, Galaeno commented on middlewares/adminValidator.js
> +  next()
Éste next está demás

2022-04-08 03:00 UTC, Galaeno commented on middlewares/adminValidator.js
> +    return res.status(401).json({
@Alacran86 ya está mergeado a main los codigos http para usar

2022-04-10 14:52 UTC, Galaeno approved these changes

2022-04-10 14:53 UTC, merged